CREATE TABLE AUTH_MEMBER
(
    AUTH_MEMBER_ID SERIAL PRIMARY KEY,
    USERNAME       VARCHAR(225) NOT NULL,
    AUTH_GROUP     VARCHAR(225) NOT NULL,
    CONSTRAINT USER_AUTH_FK FOREIGN KEY (USERNAME) REFERENCES MEMBERS (USERNAME),
    UNIQUE (USERNAME, AUTH_GROUP)
);


CREATE TABLE MEMBERS
(
    MEMBER_ID     SERIAL PRIMARY KEY,
    NAME          VARCHAR(255) NOT NULL,
    USERNAME      VARCHAR(255) NOT NULL,
    PASSWORD      VARCHAR(255) NOT NULL,
    EMAIL         VARCHAR(255) NOT NULL,
    ENABLED       BOOLEAN,
    CREATION_DATE TIMESTAMP,
    LAST_UPDATE   TIMESTAMP,
    UNIQUE (USERNAME)
);


CREATE TABLE BOOK
(
    BOOK_ID SERIAL PRIMARY KEY,
    BOOK_NAME VARCHAR(255) NOT NULL,
    BOOK_AUTHOR VARCHAR(255) NOT NULL ,
    BOOK_CODE VARCHAR(255) NOT NULL ,
    URL VARCHAR(350) NOT NULL ,
    COST INTEGER ,
    PUBLISHER VARCHAR(255) NOT NULL,
    PAGE_NUMBER INTEGER ,
    DETAILS VARCHAR(1000) NOT NULL ,
    CREATION_DATE TIMESTAMP
);

CREATE TABLE COMMENT
(
    ID SERIAL PRIMARY KEY ,
    TEXT VARCHAR(1000) NOT NULL ,
    OWNER VARCHAR(255) NOT NULL,
    DATE TIMESTAMP ,
    BOOK_ID INT ,
    CONSTRAINT BOOK_FK_CM FOREIGN KEY (BOOK_ID) REFERENCES BOOK (BOOK_ID)
);