CREATE TABLE jpa.AUTH_MEMBER(
  AUTH_MEMBER_ID SERIAL PRIMARY KEY ,
  USERNAME VARCHAR(225) NOT NULL ,
  AUTH_GROUP VARCHAR(225) NOT NULL,
  CONSTRAINT USER_AUTH_FK FOREIGN KEY (USERNAME) REFERENCES jpa.MEMBERS(USERNAME),
  UNIQUE (USERNAME, AUTH_GROUP)
);


CREATE TABLE jpa.MEMBERS(
  MEMBER_ID SERIAL PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  USERNAME VARCHAR(255) NOT NULL,
  PASSWORD VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255) NOT NULL,
  ENABLED BOOLEAN,
  CREATION_DATE TIMESTAMP,
  LAST_UPDATE   TIMESTAMP,
  UNIQUE(USERNAME)
);

CREATE TABLE jpa.VERIFICATION_TOKEN(
  ID SERIAL PRIMARY KEY,
  TOKEN VARCHAR(255) NOT NULL,
  MEMBER_FK INT NOT NULL,
  CONSTRAINT MEMBER_TOKEN_FK FOREIGN KEY (MEMBER_FK) REFERENCES jpa.MEMBERS(MEMBER_ID)
);
